# Generated by Django 5.0.4 on 2024-04-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CssSubtopic',
        ),
        migrations.DeleteModel(
            name='CssTopic',
        ),
    ]
